image: debian/stable
oauth: pages.sr.ht/PAGES:RW
environment:
    SITE: rabbits.srht.site/orca
sources:
    - https://git.sr.ht/~rabbits/orca-toy
tasks:
    - prepare: |
        curl -fsS https://rabbits.srht.site/uxn/uxn-essentials-lin64.tar.gz | tar -zx
    - build: |
        cd orca-toy
        ../uxn/uxnasm src/main.tal ../orca.rom
    - upload: |
        tar -czf out.tar.gz orca.rom
        acurl() {
            set +x
            curl -H "Authorization: Bearer ${OAUTH2_TOKEN}" "${@}"
            set -x
        }
        acurl -fsS "https://pages.sr.ht/publish/${SITE}" -Fcontent=@out.tar.gz
        acurl -fsS "https://pages.sr.ht/publish/${SITE}" -Fcontent=@out.tar.gz -Fprotocol=GEMINI