image: debian/stable
oauth: pages.sr.ht/PAGES:RW
environment:
    SITE: rabbits.srht.site/orca-toy
sources:
    - https://git.sr.ht/~rabbits/uxn11
    - https://git.sr.ht/~rabbits/orca-toy
tasks:
    - prepare: |
        cd uxn11
        cc src/uxnasm.c -o ../uxnasm
    - assemble: |
        cd orca-toy
        ../uxnasm src/orca.tal ../orca.rom
    - upload: |
        tar -czf out.tar.gz orca-toy/orca.rom
        acurl() {
            set +x
            curl -H "Authorization: Bearer ${OAUTH2_TOKEN}" "${@}"
            set -x
        }
        acurl -fsS "https://pages.sr.ht/publish/${SITE}" -Fcontent=@out.tar.gz
