image: debian/stable
packages:
- xxd
oauth: pages.sr.ht/PAGES:RW
environment:
    SITE: rabbits.srht.site/orca-toy
sources:
    - https://git.sr.ht/~rabbits/uxnmin
    - https://git.sr.ht/~rabbits/orca-toy
tasks:
    - prepare: |
        xxd -r -p uxnmin/etc/drifloon.rom.txt asm.rom
        cc -DNDEBUG -O2 -g0 -s uxnmin/src/uxnmin.c -o uxn.bin
        cat orca-toy/src/orca.tal orca-toy/src/library.tal orca-toy/src/manifest.tal orca-toy/src/assets.tal > src.tal
    - assemble: |
        cat src.tal | ./uxn.bin asm.rom > orca.rom
    - upload: |
        tar -czf out.tar.gz orca.rom
        acurl() {
            set +x
            curl -H "Authorization: Bearer ${OAUTH2_TOKEN}" "${@}"
            set -x
        }
        acurl -fsS "https://pages.sr.ht/publish/${SITE}" -Fcontent=@out.tar.gz
